a="synnefo"
b=a.upper()
print(b)
a="synnefo"
b=a.capitalize()
print(b)
# a=input("enter charactor")
# b=input("enter a letter")
# c=a.count(b)
# print(c)
# a=input("enter charactor")
# b=input("enter a letter")
# c =a.startswith(b)
# print(c)
# a=input("enter charactor")
# b=input("enter a letter")
# c =a.endswith(b)
# print(c)
# a=input("enter charactor")
# b=a.split(" ")
# b.join()
# print(b)
# txt =input("enter a sentence")
# b=input("enter  word")
# c=input("enter replace word")
# # c =txt.endswith(b)

# x = txt.replace(b, c)

# print(x)
# txt =input("enter a sentence")
# x = txt.split()
# print(x)
# y = " ".join(x)
# print(y)
